/**
 * PWA Service Worker Registration and Update Detection
 * 
 * This module handles:
 * - Service worker registration
 * - Update detection and notification
 * - Periodic update checks
 * - Integration with the app's update UI
 */

import { hardResetApp } from './resetApp';

// Build version derived from build timestamp
export const APP_VERSION = typeof __APP_VERSION__ !== 'undefined' ? __APP_VERSION__ : 'dev';

// Registration state
let swRegistration: ServiceWorkerRegistration | null = null;
let updateCallback: ((needRefresh: boolean) => void) | null = null;

// Update check interval (30 minutes)
const UPDATE_CHECK_INTERVAL = 30 * 60 * 1000;

/**
 * Register the service worker and set up update detection
 */
export async function registerSW(): Promise<ServiceWorkerRegistration | null> {
  if (!('serviceWorker' in navigator)) {
    console.log('[PWA] Service workers not supported');
    return null;
  }

  try {
    // Register the service worker generated by vite-plugin-pwa
    const registration = await navigator.serviceWorker.register('/sw.js', {
      scope: '/',
    });
    
    swRegistration = registration;
    console.log('[PWA] Service worker registered, scope:', registration.scope);
    console.log('[PWA] App version:', APP_VERSION);

    // Set up update detection
    setupUpdateDetection(registration);
    
    // Set up periodic update checks
    setupPeriodicUpdateChecks(registration);
    
    // Check for updates on visibility change (tab focus)
    setupVisibilityUpdateCheck(registration);
    
    // Check for updates when coming back online
    setupOnlineUpdateCheck(registration);

    return registration;
  } catch (error) {
    console.error('[PWA] Service worker registration failed:', error);
    return null;
  }
}

/**
 * Set up listeners for SW update events
 */
function setupUpdateDetection(registration: ServiceWorkerRegistration): void {
  // Check if there's already a waiting SW
  if (registration.waiting) {
    console.log('[PWA] Update already waiting');
    notifyUpdate(true);
  }

  // Listen for new service worker installing
  registration.addEventListener('updatefound', () => {
    const newWorker = registration.installing;
    if (!newWorker) return;

    console.log('[PWA] New service worker installing...');

    newWorker.addEventListener('statechange', () => {
      if (newWorker.state === 'installed' && navigator.serviceWorker.controller) {
        // New SW is installed and waiting
        console.log('[PWA] New version available, waiting to activate');
        notifyUpdate(true);
      }
    });
  });

  // Listen for controller change (new SW took over)
  navigator.serviceWorker.addEventListener('controllerchange', () => {
    console.log('[PWA] Controller changed, reloading...');
    window.location.reload();
  });
}

/**
 * Set up periodic update checks every 30 minutes
 */
function setupPeriodicUpdateChecks(registration: ServiceWorkerRegistration): void {
  setInterval(() => {
    console.log('[PWA] Periodic update check...');
    checkForUpdates();
  }, UPDATE_CHECK_INTERVAL);
}

/**
 * Check for updates when tab becomes visible
 */
function setupVisibilityUpdateCheck(registration: ServiceWorkerRegistration): void {
  document.addEventListener('visibilitychange', () => {
    if (document.visibilityState === 'visible') {
      console.log('[PWA] Tab focused, checking for updates...');
      checkForUpdates();
    }
  });
}

/**
 * Check for updates when coming back online
 */
function setupOnlineUpdateCheck(registration: ServiceWorkerRegistration): void {
  window.addEventListener('online', () => {
    console.log('[PWA] Back online, checking for updates...');
    checkForUpdates();
  });
}

/**
 * Manually trigger an update check
 */
export async function checkForUpdates(): Promise<void> {
  if (!swRegistration) {
    console.log('[PWA] No registration, skipping update check');
    return;
  }

  try {
    await swRegistration.update();
    
    // Check if there's a waiting SW after update
    if (swRegistration.waiting) {
      notifyUpdate(true);
    }
  } catch (error) {
    console.error('[PWA] Update check failed:', error);
  }
}

/**
 * Apply the pending update by activating the waiting SW
 */
export function applyUpdate(): void {
  if (!swRegistration?.waiting) {
    console.log('[PWA] No waiting service worker');
    return;
  }

  console.log('[PWA] Sending SKIP_WAITING to activate new SW...');
  swRegistration.waiting.postMessage({ type: 'SKIP_WAITING' });
}

/**
 * Set the callback for update notifications
 */
export function onNeedRefresh(callback: (needRefresh: boolean) => void): void {
  updateCallback = callback;
  
  // If there's already a waiting SW, notify immediately
  if (swRegistration?.waiting) {
    callback(true);
  }
}

/**
 * Notify the app about available updates
 */
function notifyUpdate(needRefresh: boolean): void {
  if (updateCallback) {
    updateCallback(needRefresh);
  }
}

/**
 * Get the current SW registration
 */
export function getRegistration(): ServiceWorkerRegistration | null {
  return swRegistration;
}
