project_id = "ftzinsesuiuqcjfpbaur"

[functions.viva-wallet]
verify_jwt = false

[functions.create-order]
verify_jwt = false

[functions.send-to-kitchen]
verify_jwt = false

[functions.update-order-status]
verify_jwt = false

[functions.update-social-post]
verify_jwt = false

[functions.confirm-payment]
verify_jwt = false

[functions.get-order]
verify_jwt = false
